import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import React from 'react';
import { TransferERC20 } from '../hooks/transfer_erc20';
import { GetERC20Data } from '../hooks/read_erc20_info';
import { GetBalanceOf } from '../hooks/read_erc20';

const Home: NextPage = () => {
  const contractAddress : `0x${string}` = "0x5FbDB2315678afecb367f032d93F642f64180aa3"; // TODO: change CA according to Network

  return (
    <div className={styles.container}>
      <Head>
        <title>ERC20 Basic Test</title>
        <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <GetERC20Data contractAddress={contractAddress} />
        <GetBalanceOf contractAddress={contractAddress} />
        <TransferERC20 contractAddress={contractAddress}/>
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Basic testing
        </a>
      </footer>
    </div>
  );
};

export default Home;
